workflows:
  build-ios-maui-altstore:
    name: Build unsigned .NET MAUI IPA for AltStore
    environment:
      xcode: latest
      vars:
        DOTNET_VERSION: "9.0.301"
        USER_NAME: "Мой пароль"  # Не рекомендуется хранить пароли прямо здесь
        PASSWORD: "Мой пароль"   # Лучше использовать секреты (secrets)
    scripts:
      - name: Install .NET SDK
        script: |
          curl -O https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh -c $DOTNET_VERSION --install-dir /usr/local/share/dotnet
          export PATH="/usr/local/share/dotnet:$PATH"
      - name: Install MAUI workload
        script: |
          dotnet workload install maui --version $DOTNET_VERSION
      - name: Restore NuGet packages
        script: |
          dotnet restore MauiApp1.csproj
      - name: Build unsigned IPA
        script: |
          dotnet build MauiApp1.csproj -f net9.0-ios -c Release -p:BuildIpa=true -p:EnableCodeSigning=false
          
      - name: Use credentials (example)
        script: |
          echo "User name is: \"$USER_NAME\""
          echo "Password is: \"$PASSWORD\""
    artifacts:
      - publish/**/*.ipa