workflows:
  build-ios-maui-altstore:
    name: Build unsigned .NET MAUI IPA for AltStore
    environment:
      groups:
        - maui_group
      vars:
        DOTNET_VERSION: "9.0.301"
    scripts:
      - name: Install .NET SDK with PATH update
        script: |
          curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version $DOTNET_VERSION --install-dir "$HOME/.dotnet"
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet --info
          
      - name: Install MAUI workload (iOS only)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet workload install maui-ios --sdk-version $DOTNET_VERSION
          dotnet workload list

      - name: Restore NuGet packages (iOS only)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet restore MauiApp1.csproj -p:TargetFramework=net9.0-ios

      - name: Build unsigned IPA (iOS only)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet build MauiApp1.csproj \
            -f net9.0-ios \
            -c Release \
            -p:BuildIpa=true \
            -p:EnableCodeSigning=false \
            -p:ArchiveOnBuild=true \
            -p:RuntimeIdentifier=ios-arm64

    artifacts:
      - bin/Release/net9.0-ios/ios-arm64/*.ipa
