workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: "3.29.3"  
      xcode: latest      
      cocoapods: default 

    vars:
      APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
      APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
      APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      # Only include if you have them:
      # CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
      # APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Build IPA (unsigned)
        script: |
          flutter build ipa --release \
          --dart-define=APP_ENV=production \
          --no-codesign  # Add this flag if you're not signing
          
          # Alternative for development/debugging:
          # flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    # Only enable publishing when you have proper signing setup
    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    #     key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    #     issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    #   email:
    #     recipients:
    #       - your-email@example.com