workflows:
  build-ios-maui-altstore:
    name: Build unsigned .NET MAUI IPA for AltStore
    environment:
      groups:
        - maui_group
      vars:
        DOTNET_VERSION: "9.0.301"
    scripts:
      - name: Install .NET SDK with PATH update
        script: |
          curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel $DOTNET_VERSION --install-dir "$HOME/.dotnet"
          echo 'export PATH="$HOME/.dotnet:$PATH"' >> ~/.zshrc
          source ~/.zshrc
          dotnet --version
      - name: Install MAUI workload
        script: |
          dotnet workload install maui-ios --version $DOTNET_VERSION
          dotnet workload list
      - name: Restore NuGet packages
        script: |
          dotnet restore MauiApp1.csproj
      - name: Build unsigned IPA
        script: |
          dotnet build MauiApp1.csproj -f net9.0-ios -c Release -p:BuildIpa=true -p:EnableCodeSigning=false -p:ArchiveOnBuild=true
    artifacts:
      - bin/Release/net9.0-ios/ios-arm64/*.ipa