workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: "3.29.3"  
      xcode: latest      
      cocoapods: default 

    # Настройки для iOS-специфичных переменных
    vars:
      APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
      APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
      APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY

    scripts:
      - name: Установка зависимостей
        script: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Сборка IPA
        script: |
          flutter build ipa --release \
          --export-options-plist=ios/ExportOptions.plist \
          --dart-define=APP_ENV=production

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect: # Автоматическая загрузка в App Store Connect
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - your-email@example.com