workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: "3.29.3"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA (unsigned)
        script: |
          flutter build ipa \
            --release \
            --no-codesign \
            --dart-define=APP_ENV=production

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.plist
      - /tmp/xcodebuild_logs/*.log
