scripts:
  - name: Install Flutter dependencies
    script: |
      cd app
      flutter pub get

  - name: Install CocoaPods dependencies
    script: |
      cd app/ios
      pod install --repo-update
      cd ../..

  - name: Build IPA (unsigned)
    script: |
      cd app
      flutter build ipa --release --no-codesign --dart-define=APP_ENV=production
